### PR TITLE
Khushvind Maurya 2021MT10238 WEB

### PR DESCRIPTION
**Pull request by khushvind**
Added links for my Insta, Git, Linkedin and Facebook accounts and also added link to profile pic

### CODE REVIEW

**Comment by shubham1206agra** [comment]
Please resolve conflicts

**Comment by khushvind** [comment]
> Please resolve conflicts

I have resolved the conflicts

**Comment by khushvind** [comment]
> Please resolve conflicts
Please merge my pull request now

**Comment by shubham1206agra** [comment]
idts :(

**Comment by khushvind** [comment]
> idts :(

Now?

**Pull request merged**
