### PR TITLE
PriyanshiTayal 2021ME10999 WEB

### PR DESCRIPTION
**Pull request by PriyanshiTayal**

### CODE REVIEW

**Comment by shubham1206agra** [comment]
pls resolve conflicts.

**Comment by PriyanshiTayal** [comment]
Resolved sir. Do I also have click on 'commit merge' after that?

**Comment by PriyanshiTayal** [comment]
resolved and I merged

**Comment by PriyanshiTayal** [comment]
Pls tell, is it fine now?

**Pull request merged**
